export const analysisSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    summary: { type: "string" },
    program: { type: ["string", "null"] },
    status: { type: ["string", "null"] },
    applicant_eligibility: { type: "array", items: { type: "string" } },
    eligible_activities: { type: "array", items: { type: "string" } },
    budget_text: { type: ["string", "null"] },
    cofinancing_text: { type: ["string", "null"] },
    region_text: { type: ["string", "null"] },
    deadline_text: { type: ["string", "null"] },
    deadline_at: {
      type: ["string", "null"],
      description: "ISO date YYYY-MM-DD if a clear deadline exists, otherwise null.",
    },
    relevance_score: {
      type: "number",
      minimum: 0,
      maximum: 100,
    },
    recommendation: { type: "string" },
    risks: { type: "array", items: { type: "string" } },
    manual_checks: { type: "array", items: { type: "string" } },
    keywords: { type: "array", items: { type: "string" } },
  },
  required: [
    "summary",
    "program",
    "status",
    "applicant_eligibility",
    "eligible_activities",
    "budget_text",
    "cofinancing_text",
    "region_text",
    "deadline_text",
    "deadline_at",
    "relevance_score",
    "recommendation",
    "risks",
    "manual_checks",
    "keywords",
  ],
} as const;
